// swift-tools-version: 5.9
import PackageDescription

// Manifest for the public distribution repo
// https://github.com/samsarahq/ble-network-sdk
//
// Generated by `just publish-repo-root`; 0.2.0 and 6011845f4d9c0b03d7a023ee8ebb0bd1bfeb5058b1440498bb835b08d5aa7afb are
// substituted from VERSION and the built zip. Do not edit the published copy —
// that branch's tree is replaced on every release.
//
// This is the *binary* channel and the only one published. A partner compiles
// none of our code: SwiftPM fetches the XCFramework from the release asset for
// this tag and verifies the checksum below before using it. The source manifest
// at sdk/ios/export/Package.swift is built and tested in the monorepo but is
// not published; see PACKAGING.md.
//
// Two things here are load-bearing and easy to "tidy" into a broken release:
//
//   - No .macOS platform. The XCFramework carries device and simulator iOS
//     slices only, so declaring macOS advertises a platform that cannot link,
//     and `swift build` on a Mac then fails on slice selection rather than on
//     anything a host did wrong.
//   - No dependencies. Nordic's iOS-BLE-Library and SamsaraStatecharts are
//     statically linked into the binary and hidden from its .swiftinterface.
//     Naming either here would make a consumer resolve a package they cannot
//     reach — SamsaraStatecharts lives in a private org.
let package = Package(
    name: "SamsaraBLE",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "SamsaraBLE", targets: ["SamsaraBLE"]),
    ],
    targets: [
        .binaryTarget(
            name: "SamsaraBLE",
            url: "https://github.com/samsarahq/ble-network-sdk/releases/download/v0.2.0/SamsaraBLE-0.2.0.xcframework.zip",
            checksum: "6011845f4d9c0b03d7a023ee8ebb0bd1bfeb5058b1440498bb835b08d5aa7afb"
        ),
    ]
)
