{
  "formatVersion": "1.1",
  "component": {
    "group": "com.samsara.ble",
    "module": "samsara-ble-sdk",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "samsara-ble-sdk-0.2.0.aar",
          "url": "samsara-ble-sdk-0.2.0.aar",
          "size": 1757817,
          "sha512": "aad5da16aa5ed086f9178de9b2b36e8a3e0c9925a14db0b9f9ae82c86918c792a750e5a49173f30fac5d8f0dfee9be93e38b87e19ed54812747eba4d4d2feb0c",
          "sha256": "15031d4074353e5c0683bb78baad33e2ebebd3eaefd2afa6e53735975b2c59cc",
          "sha1": "44deb9a5386d49e721d591f5a44b62d7806da6ec",
          "md5": "bcbcca453a9deb48b786b7c68d8085d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "samsara-ble-sdk-0.2.0.aar",
          "url": "samsara-ble-sdk-0.2.0.aar",
          "size": 1757817,
          "sha512": "aad5da16aa5ed086f9178de9b2b36e8a3e0c9925a14db0b9f9ae82c86918c792a750e5a49173f30fac5d8f0dfee9be93e38b87e19ed54812747eba4d4d2feb0c",
          "sha256": "15031d4074353e5c0683bb78baad33e2ebebd3eaefd2afa6e53735975b2c59cc",
          "sha1": "44deb9a5386d49e721d591f5a44b62d7806da6ec",
          "md5": "bcbcca453a9deb48b786b7c68d8085d9"
        }
      ]
    }
  ]
}
