{
  "formatVersion": "1.1",
  "component": {
    "group": "com.samsara.ble",
    "module": "samsara-ble-sdk",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "samsara-ble-sdk-0.1.1.aar",
          "url": "samsara-ble-sdk-0.1.1.aar",
          "size": 1750388,
          "sha512": "31f6ca47c9febc9253d421ac38a8d77832e4be7b6049ca444e2b11b75983e1f5240153e9197e53bdbb888aeb2108f1e7cde056b29c32ef0513fec11461d7daa5",
          "sha256": "28c8ff3082cac435d57c473c99ba1de9e534b6a05935ffad507e47f8907afc63",
          "sha1": "1f40b1272abf99c1a9253a4d6b6267b12c3743c2",
          "md5": "92d0a4f26ab52c10af318968597dc389"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "samsara-ble-sdk-0.1.1.aar",
          "url": "samsara-ble-sdk-0.1.1.aar",
          "size": 1750388,
          "sha512": "31f6ca47c9febc9253d421ac38a8d77832e4be7b6049ca444e2b11b75983e1f5240153e9197e53bdbb888aeb2108f1e7cde056b29c32ef0513fec11461d7daa5",
          "sha256": "28c8ff3082cac435d57c473c99ba1de9e534b6a05935ffad507e47f8907afc63",
          "sha1": "1f40b1272abf99c1a9253a4d6b6267b12c3743c2",
          "md5": "92d0a4f26ab52c10af318968597dc389"
        }
      ]
    }
  ]
}
