{
  "formatVersion": "1.1",
  "component": {
    "group": "com.samsara.ble",
    "module": "samsara-ble-sdk",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "samsara-ble-sdk-0.1.2.aar",
          "url": "samsara-ble-sdk-0.1.2.aar",
          "size": 1757729,
          "sha512": "91eeb69af871b298b45f442d4f3f3e50f6ea02cbc657235becc7717fbed1f2d1b35fc4344b5f228d302b85adb5661e1d083c250e5e0fa626398bcd5d63e3de16",
          "sha256": "f0951f1f2421936fc7f3299b8a5fa9b5cc3aefb05280a2864e7f685fa02f162f",
          "sha1": "af690a91d6a24f725731bd202a819ad5b2578290",
          "md5": "c0ee81c5aff3a355ef7bd0d158220d51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "samsara-ble-sdk-0.1.2.aar",
          "url": "samsara-ble-sdk-0.1.2.aar",
          "size": 1757729,
          "sha512": "91eeb69af871b298b45f442d4f3f3e50f6ea02cbc657235becc7717fbed1f2d1b35fc4344b5f228d302b85adb5661e1d083c250e5e0fa626398bcd5d63e3de16",
          "sha256": "f0951f1f2421936fc7f3299b8a5fa9b5cc3aefb05280a2864e7f685fa02f162f",
          "sha1": "af690a91d6a24f725731bd202a819ad5b2578290",
          "md5": "c0ee81c5aff3a355ef7bd0d158220d51"
        }
      ]
    }
  ]
}
